rpihelper/services/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import TextField, SelectField
from wtforms.validators import ValidationError, DataRequired, Length

from rpihelper.services.logic import SystemctlCommands, get_services

__all__ = (
    'ServicesForm',
)


class ServicesForm(Form):
    service = TextField('Service name', validators=(
        DataRequired(),
        Length(min=1, max=20),
    ))
    command = SelectField('Command', choices=(
        (SystemctlCommands.START, 'Start',),
        (SystemctlCommands.STOP, 'Stop',),
        (SystemctlCommands.RESTART, 'Restart',),
    ))

    def validate_service(form, field):
        services_names = [
            service['name'] for service in get_services()
        ]

        if field.data not in services_names:
            raise ValidationError('Unknown service name')

rpihelper/__init__.py
# -*- coding: utf-8 -*-

from rpihelper.app import create_app

rpihelper/app.py
# -*- coding: utf-8 -*-

import functools
import os
import os.path

from flask_wtf.csrf import CsrfProtect

from flask import render_template

from rpihelper.config import Flask
from rpihelper.rpihelper import rpihelper
from rpihelper.services import services
from rpihelper.sysmonitor import sysmonitor

__all__ = (
    'create_app',
)


APP_NAME = 'rpihelper'

DEFAULT_BLUEPRINTS = (
    rpihelper,
    services,
    sysmonitor,
)


@functools.lru_cache()
def create_app(blueprints=None, testing=False):
    if not blueprints:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(APP_NAME)
    configure_app(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_hook(app)
    configure_error_handlers(app)
    configure_additional_directories(app)

    return app


def configure_app(app):
    config_file = os.environ.get(
        'FLASK_CONFIG_FILE',
        '%s/config_local.yaml' % app.config['PROJECT_ROOT']
    )
    app.config.from_yaml(config_file)


def configure_extensions(app):
    # Flask-WTF
    csrf = CsrfProtect()
    csrf.init_app(app)


def configure_blueprints(app, blueprints):
    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):

    @app.template_filter()
    def pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)


def configure_logging(app):
    if app.debug or app.testing:
        # Skip debug and test mode. Just check standard output.
        return

    import logging, logging.handlers

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_DIR'], 'info.log')
    info_file_handler = logging.handlers.RotatingFileHandler(info_log, maxBytes=100000, backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    #app.logger.info('testing info.')
    #app.logger.warn('testing warn.')
    #app.logger.error('testing error.')


def configure_hook(app):
    @app.before_request
    def before_request():
        pass


def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template('errors/403.html'), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template('errors/404.html'), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template('errors/500.html'), 500


def configure_additional_directories(app):
    pass

rpihelper/dropboxclient/__init__.py
# -*- coding: utf-8 -*-

rpihelper/rpihelper/__init__.py
# -*- coding: utf-8 -*-

from .views import rpihelper

rpihelper/rpihelper/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template

__all__ = (
    'rpihelper',
)


rpihelper = Blueprint(
    'rpihelper',
    __name__,
    url_prefix='/',
    template_folder='templates',
    static_folder='static'
)


@rpihelper.route('/', methods=('GET',))
def index():
    return render_template('rpihelper/index.html')

rpihelper/services/__init__.py
# -*- coding: utf-8 -*-

from .views import services

rpihelper/services/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, jsonify

from rpihelper.services.forms import ServicesForm
from rpihelper.services.logic import get_services_with_status, systemctl_ssr_command

__all__ = (
    'ERR_EXECUTE_COMMAND',

    'services',
)


ERR_EXECUTE_COMMAND = 'An error occurred while executing command "%s" for service "%s"'


services = Blueprint(
    'services',
    __name__,
    url_prefix='/services',
    template_folder='templates',
    static_folder='static'
)


@services.route('/', methods=('GET',))
def index():
    return render_template('services/index.html', **{
        'services': get_services_with_status(),
    })


@services.route('/send_service_command/', methods=('POST',))
def send_service_command():
    form = ServicesForm()

    if form.validate_on_submit():
        command = form.command.data
        service = form.service.data

        error = systemctl_ssr_command(command, service)
        if error:
            error = ERR_EXECUTE_COMMAND % (command, service)
            return jsonify(status='error', error=error)

        return jsonify(status='ok')

    return jsonify(status='error', errors=form.errors)

rpihelper/sysmonitor/__init__.py
# -*- coding: utf-8 -*-

from .views import sysmonitor

rpihelper/sysmonitor/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, jsonify

from rpihelper.sysmonitor.logic import get_system_info

__all__ = (
    'sysmonitor',
)


sysmonitor = Blueprint(
    'sysmonitor',
    __name__,
    url_prefix='/sysmonitor',
    template_folder='templates',
    static_folder='static'
)


@sysmonitor.route('/', methods=('GET',))
def index():
    return render_template('sysmonitor/index.html')


@sysmonitor.route('/system_info/', methods=('POST',))
def system_info():
    return jsonify(status='ok', data=get_system_info())

rpihelper/transmission/__init__.py
# -*- coding: utf-8 -*-

rpihelper/rpihelper/templates/rpihelper/index.html
{% extends 'layouts/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to Raspberry Pi!</h1>
        <p class="lead">Stay with us!</p>
    </div>
{% endblock %}

rpihelper/services/templates/services/_scripts.html
<script type="text/javascript">
    window.Settings = window.Settings || {};
    window.Settings.Services = {
        sendServiceCommandUrl: "{{ url_for('services.send_service_command') }}"
    };
</script>

<script type="text/javascript" charset="utf-8" src="{{ url_for('services.static', filename='services/js/services.js') }}"></script>

rpihelper/services/templates/services/_templates.html
<script type="text/template" id="js-tmpl-services-service-commands-active">
    <button type="button" class="btn btn-default btn-info js-services-call-command"
            data-service="<%= service %>" data-command="restart">Restart</button>
    <button type="button" class="btn btn-default btn-danger js-services-call-command"
            data-service="<%= service %>" data-command="stop">Stop</button>
</script>

<script type="text/template" id="js-tmpl-services-service-commands-inactive">
    <button type="button" class="btn btn-default btn-success js-services-call-command"
            data-service="<%= service %>" data-command="start">Start</button>
</script>

rpihelper/services/templates/services/index.html
{% extends 'layouts/base.html' %}

{% block title %}Services{% endblock %}

{% macro commands_active(service_name) -%}
    <button type="button" class="btn btn-default btn-info js-services-call-command"
            data-service="{{ service_name }}" data-command="restart">Restart</button>
    <button type="button" class="btn btn-default btn-danger js-services-call-command"
            data-service="{{ service_name }}" data-command="stop">Stop</button>
{%- endmacro %}

{% macro commands_inactive(service_name) -%}
    <button type="button" class="btn btn-default btn-success js-services-call-command"
            data-service="{{ service_name }}" data-command="start">Start</button>
{%- endmacro %}

{% block content %}
    <h2>Services</h2>
    {% if services -%}
    <table id="js-services-content" class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Link</th>
                <th>Commands</th>
            </tr>
        </thead>
        <tbody>
            {% for service in services -%}
            <tr class="js-services-service-{{ service.name }}">
                <td>{{ service.name }}</td>
                <td>{{ service.description }}</td>
                <td><a href="{{ service.url }}">{{ service.url }}</a></td>
                <td class="js-services-service-commands">
                    {% if service.status == 'active' -%}
                        {{ commands_active(service.name) }}
                    {% else %}
                        {{ commands_inactive(service.name) }}
                    {%- endif %}
                </td>
            </tr>
            {%- endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-info">
        <strong>Ops!</strong> Services not found...
    </div>
    {%- endif %}
{% endblock %}

{% block extra_scripts %}
    {% include 'services/_scripts.html' %}
{% endblock %}

{% block extra_templates %}
    {% include 'services/_templates.html' %}
{% endblock %}

rpihelper/sysmonitor/templates/sysmonitor/_scripts.html
<script type="text/javascript">
    window.Settings = window.Settings || {};
    window.Settings.SysMonitor = {
        systemInfoUrl: "{{ url_for('sysmonitor.system_info') }}"
    };
</script>

<script type="text/javascript" charset="utf-8" src="{{ url_for('sysmonitor.static', filename='sysmonitor/js/sysmonitor.js') }}"></script>

rpihelper/sysmonitor/templates/sysmonitor/_templates.html
<script type="text/template" id="js-tmpl-sysmonitor-system-info">
    <div class="row">
        <div class="col-lg-6">
            <h3>General:</h3>
            <p><strong>Boot time:</strong> <%= boot_time %></p>
            <p><strong>Temperature:</strong> <%= temperature %></p>
        </div>
        <div class="col-lg-6">
            <h3>Voltage:</h3>
            <p><strong>Core:</strong> <%= voltage.core %></p>
            <p><strong>I/O:</strong> <%= voltage.io %></p>
            <p><strong>PHY:</strong> <%= voltage.phy %></p>
            {#<h3>CPU:</h3>
            <% _.each(cpu, function(c) { %>
                <div class="progress progress-striped">
                    <div class="progress-bar progress-bar-info" style="width: <%= c %>%"></div>
                </div>
            <% }); %>#}
        </div>
    </div>

    <h3>CPU:</h3>
    <% _.each(cpu, function(c) { %>
        <div class="progress progress-striped">
            <div class="progress-bar progress-bar-info" style="width: <%= c %>%"></div>
        </div>
    <% }); %>

    <div class="row">
        <div class="col-lg-6">
            <h3>RAM:</h3>
            <p><strong>Total:</strong> <%= virtual_memory.total %>; <strong>Used:</strong> <%= virtual_memory.used %></p>
            <div class="progress progress-striped">
                <div class="progress-bar progress-bar-info" style="width: <%= virtual_memory.percent %>%"></div>
            </div>
        </div>
        <div class="col-lg-6">
            <h3>SWAP:</h3>
            <p><strong>Total:</strong> <%= swap_memory.total %>; <strong>Used:</strong> <%= swap_memory.used %></p>
            <div class="progress progress-striped">
                <div class="progress-bar progress-bar-info" style="width: <%= swap_memory.percent %>%"></div>
            </div>
        </div>
    </div>

    <h3>Disks:</h3>
    <% _.each(disks, function(disk) { %>
        <p><strong>Mountpoint:</strong> <%= disk.mountpoint %>; <strong>Total:</strong> <%= disk.total %>; <strong>Used:</strong> <%= disk.used %></p>
        <div class="progress progress-striped">
            <div class="progress-bar progress-bar-info" style="width: <%= disk.percent %>%"></div>
        </div>
    <% }); %>

    <h3>Processes:
        <% _.each(processes[1], function(count, status) { %>
            <span class="label label-default"><%= status %>: <%= count %></span>
        <% }); %>
    </h3>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>PID</th>
                <th>User</th>
                <th>NI</th>
                <th>CPU%</th>
                <th>MEM%</th>
                <th>Time+</th>
                <th>Command</th>
            </tr>
        </thead>
        <tbody>
            <% _.each(processes[0], function(process) { %>
            <tr>
                <td><%= process.pid %></td>
                <td><%= process.username %></td>
                <td><%= process.nice %></td>
                <td><%= process.cpu_percent %></td>
                <td><%= process.memory_percent %></td>
                <td><%= process.cpu_times_system %></td>
                <td><%= process.name %></td>
            </tr>
            <% }); %>
        </tbody>
    </table>
</script>

rpihelper/sysmonitor/templates/sysmonitor/index.html
{% extends 'layouts/base.html' %}

{% block title %}System monitor{% endblock %}

{% block content %}
    <h2>System monitor</h2>

    <div id="js-sysmonitor-content">
        <div class="throbber"></div>
    </div>
{% endblock %}

{% block extra_scripts %}
    {% include 'sysmonitor/_scripts.html' %}
{% endblock %}

{% block extra_templates %}
    {% include 'sysmonitor/_templates.html' %}
{% endblock %}

rpihelper/templates/components/_base_pluginscripts.html
<script type="text/javascript" charset="utf-8" src="{{ url_for('static', filename='plugins/js/jquery/jquery-2.0.3.min.js') }}"></script>
<script type="text/javascript" charset="utf-8" src="{{ url_for('static', filename='plugins/js/underscore/underscore-min.js') }}"></script>
<script type="text/javascript" charset="utf-8" src="{{ url_for('static', filename='plugins/js/backbone/backbone-min.js') }}"></script>
<script type="text/javascript" charset="utf-8" src="{{ url_for('static', filename='plugins/js/bootstrap/bootstrap.min.js') }}"></script>

rpihelper/templates/components/_base_scripts.html
<script type="text/javascript">
(function(settings, $, window, undefined) {
    var csrftoken = $('meta[name=csrf-token]').attr('content');

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader('X-CSRFToken', csrftoken);
            }
        }
    });
})(window.Settings || {}, jQuery, window);
</script>

<script type="text/javascript" charset="utf-8" src="{{ url_for('static', filename='base/js/application.js') }}"></script>
<script type="text/javascript" charset="utf-8" src="{{ url_for('static', filename='base/js/forms.js') }}"></script>

rpihelper/templates/components/_footer.html
<div class="footer">
    <p>&copy; 2013 Nikita Grishko</p>
</div>

rpihelper/templates/components/_header.html
<div class="header">
    <ul class="nav nav-pills pull-right">
        <li><a href="{{ url_for('rpihelper.index') }}">Home</a></li>
        <li><a href="{{ url_for('sysmonitor.index') }}">System monitor</a></li>
        <li><a href="{{ url_for('services.index') }}">Services</a></li>
    </ul>
    <h3 class="text-muted brand"><img src="{{ url_for('static', filename='base/img/rpi_logo.png') }}" alt="{{ config.PROJECT }}"></h3>
</div>

rpihelper/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="RPiHelper">
    <meta name="author" content="Nikita Grishko">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="Shortcut Icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <title>{% block title %}{% endblock %} - RPi Helper</title>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='plugins/css/bootstrap/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='base/css/style.css') }}">
</head>

<body>
    <div class="container-main">
        <div class="container-narrow">
            {% include 'components/_header.html' %}

            {% block content %}{% endblock %}
        </div>
    </div>

    {% include 'components/_footer.html' %}

    {% include 'components/_base_pluginscripts.html' %}
    {% block extra_pluginscripts %}{% endblock %}
    {% include 'components/_base_scripts.html' %}
    {% block extra_scripts %}{% endblock %}

    {% block extra_templates %}{% endblock %}
</body>
</html>